CREATE OR REPLACE NOTIFICATION INTEGRATION EMAIL_NOTIFICATION_INTEGRATION TYPE = EMAIL ENABLED = TRUE ALLOWED_RECIPIENTS = ('ab@c.com');

SELECT * FROM TABLE(SNOWFLAKE.INFORMATION_SCHEMA.ALERT_HISTORY(SCHEDULED_TIME_RANGE_START => DATEADD('day', -1, CURRENT_TIMESTAMP()))) ORDER BY SCHEDULED_TIME;
